Repository obi-wan-shinobi/BE-Project-Documentation, pull requests merged in 2020-12, with the labels that each got.

#11 Hrushikesh
  Literature Review/References.bib
  Literature Review/Review.aux
  Literature Review/Review.bbl
  Literature Review/Review.blg
  Literature Review/Review.fdb_latexmk
  Literature Review/Review.fls
  Literature Review/Review.log
  Literature Review/Review.pdf
  Literature Review/Review.synctex.gz
  Literature Review/Review.tex
  Papers/Upscaling/tian2011.pdf
Labels: documentation

#14 Stage 1 report init and abstract
  Report/Stage_1/report.aux
  Report/Stage_1/report.log
  Report/Stage_1/report.pdf
  Report/Stage_1/report.synctex.gz
  Report/Stage_1/report.tex
Labels: documentation

#32 Combining changes
  .gitignore
  Literature Review/Review.pdf
  Report/Stage_1/report.pdf
  Report/Stage_1/report.tex
  Report/Stage_1/use.jpg
Labels: documentation

#27 Motivation, literature survey, constraints, methodologies, GPU scenarios, outcomes and h/w & s/w requirements
  .gitignore
  Literature Review/Review.pdf
  README.md
  Report/Stage_1/biblo.bib
  Report/Stage_1/figures/discriminator_color.jpg
  Report/Stage_1/figures/encoder_decoder_generator_color.jpg
  Report/Stage_1/figures/ledig_srgan_architecture.jpg
  Report/Stage_1/figures/levin_scribble_based_colorization_example.jpg
  Report/Stage_1/report.pdf
  Report/Stage_1/report.tex
  Report/Stage_1/tables/hardware_requirements.tex
  Report/Stage_1/use.jpg
Labels: documentation, enhancement

#33 Minor bug fixes
  Literature Review/Review.pdf
  Report/Stage_1/figures/use.jpg
  Report/Stage_1/report.pdf
  Report/Stage_1/report.tex
  Report/Stage_1/tables/use_case_table.tex
Labels: bug

#38 Chronological Literature Review Table
  Literature Review/Review.pdf
  Presentation/Stage_1/figures/block_diagrams/GAN/GAN.pdf
  Presentation/Stage_1/figures/block_diagrams/discriminator_color.jpg
  Presentation/Stage_1/figures/block_diagrams/encoder_decoder_generator_color.jpg
  Presentation/Stage_1/figures/block_diagrams/ledig_srgan_architecture.jpg
  Presentation/Stage_1/tables/literature_review.pdf
  Presentation/Stage_1/tables/literature_review.tex
  Report/Stage_1/figures/activity_diagram.tikz
  Report/Stage_1/figures/state_transition_diagram.tikz
  Report/Stage_1/report.pdf
  Report/Stage_1/report.tex
  Report/Stage_1/tables/literature_review.tex
Labels: documentation

#39 PPT added
  Presentation/Stage_1/stage_1_report_ppt.pptx
  Presentation/Stage_1/tables/literature_review.pdf
  Presentation/Stage_1/tables/literature_review.tex
Labels: documentation
